config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :comments
  resources :messages

  resources :messages do
    resources :comments
  end

  root 'sessions#welcome'

  resource :sessions

  resources :users, except: :index

  get 'homepage' => 'sessions#homepage'

  get 'logout' => 'sessions#logout'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
end

app/models/message.rb
class Message < ActiveRecord::Base
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

  validates :first_name, :last_name, :address, :zip, presence: :true
  validates :zip, numericality: { only_integer: true}, length: {maximum: 5}
  validates :email, presence: :true, uniqueness: :true, confirmation: :true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :email_confirmation, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :check_logged_in, except: [:welcome, :new]

  # def check_logged_in
  #   @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])

  #   unless @user
  #     redirect_to root_path
  #   end
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_message, only: [:new, :create]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @message.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.message, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment.message, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_message
      @message = Message.find(params[:message_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :message_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  def index
    @messages = Message.all
    @message = Message.new
  end

  # GET /messages/1
  def show
    render layout: !request.xhr?
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  def create
    @message = Message.new(message_params)
      if @message.save
        redirect_to @message, notice: 'Message was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /messages/1
  def update
      if @message.update(message_params)
        redirect_to @message, notice: 'Message was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy
    redirect_to messages_url, notice: 'Message was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_user, only: [:homepage]
  after_action :forget_user, only: [:logout]

  def new
  end

  def welcome
  end

  def homepage
    session[:user_id] = @user.id
  end

  def logout
    reset_session
  end

  def create
    @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])

 	  if @user
 	    session[:user_id] = @user.id
 	    redirect_to homepage_path
 	  else
 	    render action: 'new'
 	  end
  end

  private
  def set_user
    @user = User.find_by(params[:email])
  end

  def forget_user
    @user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def show
  end

  def edit
  end

  def destroy
    @user.destroy

    redirect_to root_path, notice: 'User was successfully destroyed'
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to homepage_path, notice: 'User was successfully created.'
    else
      redirect_to root_path
    end
  end

  def update
    if @user.update(user_params)
      html{redirect_to @user, notice: 'User was successfully updated.'}
    else
      html{render :new}
    end
  end


  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :address, :zip, :password, :password_confirmation, :email, :email_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <%= comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(comment) %>
<hr>

app/views/comments/_form.html.erb
<%= form_for([@message, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Comment' %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<br><br><br><br>
<div class="container message-show">
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Delete', @comment, method: :delete, data: {confirm: 'Are you sure?'} %> |
<%= link_to 'Back', @comment.message %>
</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.message %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<br><br><br><br>
<div class="container new-comment message-show">
  <h1>New Comment for: </h1>
  <h4>Topic: <%= @message.title %></h4>
  <h4>Body: <%= @message.description %></h4>
  <%= render 'form' %>
  <%= link_to 'Back', @message %>
</div>

app/views/comments/show.html.erb
<p>
  <strong>Comment:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @comment.message.title %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', @comment.message %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doc Loc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="assets/bootstrap.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">
  <!-- Custom CSS -->
  <link href="assets/freelancer.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
      </head>
      <body id="page-top" class="<%= controller_name %> <%= action_name %>">
        <%#= notice %>
        <%= alert %>
        <ul>
          <% if session[:user_id] %>
          <%#= link_to 'Edit Account', edit_user_path(@user) %>
          <%= link_to 'Sign Out', logout_path %>
          <!-- <a href="tel:911">Emergency</a> -->
          <%= link_to "Home", homepage_path %>
          <%= link_to "Health Forum", messages_path %>
          <% else %>

          <%= link_to 'Sign In', new_sessions_path %>
          <%= link_to 'Sign Up', new_user_path %>
          <% end %>
        </ul>
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

              <a class="navbar-brand" href="/">Doc Loc</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <% if session[:user_id] %>
                <!-- Considered adding Emergency button. Makes more sense when we go mobile -->
                <!-- <li><a href="tel:911">Emergency</a></li> -->
                <li><%= link_to "Home", homepage_path %></li>
                <li><%= link_to "Health Forum", messages_path %></li>
                <li><%= link_to 'Sign Out', logout_path %></li>
                <% else %>
                <li class="hidden">
                  <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                  <a href="#about">About</a>
                </li>
                <!-- <li class="page-scroll">
                  <a href="#portfolio">Founders</a>
                </li>
                <li class="page-scroll">
                  <a href="#contact">Contact</a>
                </li> -->
                <li><%= link_to 'Sign In', new_sessions_path %></li>
                <li><%= link_to 'Sign Up', new_user_path %></li>
                <% end %>
              </ul>
            </div>
            <!-- /.navbar-collapse -->
          </div>
          <!-- /.container-fluid -->
        </nav>

        <%= yield %>

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

        <!-- Plugin JavaScript -->
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
        <script src="assets/classie.js"></script>
        <script src="assets/cbpAnimatedHeader.min.js"></script>

        <!-- Contact Form JavaScript -->
        <script src="assets/jqBootstrapValidation.js"></script>
        <script src="assets/contact_me.js"></script>

        <!-- Custom Theme JavaScript -->
        <script src="assets/freelancer.js"></script>
      </body>
      </html>

app/views/messages/_form.html.erb
<div class="col-md-12 text-center">
  <%= form_for(@message, remote: true) do |f| %>
  <% if @message.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

    <ul>
      <% @message.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <!-- Form used for forum only, seperate css and bootstrap class identifiers than the signin/signup forms -->
  <div class="field">
    <%= f.label 'Topic' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <a class='btn-custom'><%= f.submit %></a>
  </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<p><strong>Topic:</strong>
	<%= link_to message.title, message %>
</p>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<br><br><br><br>
<h1 class='container forum-title well'><br>Welcome to the Doc Loc Forum</h1>
<div class="message-list">
  <% @messages.each do |message| %>
  <div class='col-md-4'>
    <div class='message'>
      <%= render message %>
      <p>Comments: <%= message.comments.count %></p>
      <br>
      <a class='btn-custom'<%= link_to 'View Discussion', message %>></a>
    </div>
  </div>
  <% end %>
</div>
<br>
<!-- SIMPLIFIED SIGNUP/SIGNIN FORM TEMPLATE BELOW, USED HERE FOR CREATING NEW MESSAGE TOPICS -->
<%= render 'form' %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<br><br><br><br><br>
<div class="container">
  <div class='col-md-8 col-md-offset-2'>
    <div class='message-show'>
      <p>
       <h2><%= @message.title %></h2>
       <p><%= @message.description %></p>
     </p>
     <h3>Comments</h3>
     <%= render @message.comments %>
     <p>
      <a class='btn-custom'<%= link_to 'New Comment',
      new_message_comment_path(@message) %></a>
    </p>
    <%= link_to 'Back', messages_path %>
  </div>
</div>
</div>

app/views/users/_signup.html.erb
<br><br><br><br><br><br><br>
<div class="form container col-md-4 text-center">
  <%= form_for(@user) do |f| %>
  <div class="header">
    <h3>New User Sign Up</h3>
    <p>Please fill out the form below</p>
  </div>
  <!-- Form is used for new member signup only. contains additional info to be stored and accessed later -->
  <div class="inputs">
    <%= f.text_field :first_name, placeholder: 'First Name', autofocus: true%>
    <%= f.text_field :last_name, placeholder: 'Last Name' %>
    <%= f.email_field :email, placeholder:'Email' %><%= f.email_field :email_confirmation, placeholder:'Email Confirmation' %>
    <%= f.password_field :password, placeholder:'Password' %>
    <%= f.password_field :password_confirmation, placeholder:'Password Confirmation' %>
    <%= f.text_field :address, placeholder: 'Address' %>
    <%= f.text_field :zip, placeholder: 'Zip Code' %>
    <%= f.submit'Submit', class: "login" %>
  </div>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>
<%= link_to "Home", root_path %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>
<%= link_to "Home", root_path %>

app/views/users/edit.html.erb
<h1>Edit user info</h1>

<%= render 'signup' %>

<%= link_to "Back", homepage_path %>

app/views/users/new.html.erb
<%= render 'signup' %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= link_to "Home", root_path %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>
<%= link_to "Home", root_path %>